USE sales_analytics;

-- =====================================================
-- Analytics Queries
-- Project: Sales Analytics Learning System
-- Purpose:
-- These queries explain the business logic behind the analytics layer.
-- They can be used for SQL practice, portfolio explanation, and validation.
-- =====================================================


-- =====================================================
-- 1. Total Revenue
-- Business Purpose:
-- Shows total sales value generated by the business.
-- =====================================================

SELECT
    SUM(total_sales) AS total_revenue
FROM sales;


-- =====================================================
-- 2. Total Orders
-- Business Purpose:
-- Shows total number of sales transactions.
-- =====================================================

SELECT
    COUNT(*) AS total_orders
FROM sales;


-- =====================================================
-- 3. Average Order Value
-- Business Purpose:
-- Shows average revenue generated per order.
-- Formula: Total Revenue / Total Orders
-- =====================================================

SELECT
    ROUND(SUM(total_sales) / COUNT(*), 2) AS average_order_value
FROM sales;


-- =====================================================
-- 4. Unique Customers
-- Business Purpose:
-- Shows how many unique customers are present in the sales data.
-- =====================================================

SELECT
    COUNT(DISTINCT customer_name) AS unique_customers
FROM sales;


-- =====================================================
-- 5. Overall KPI Summary
-- Business Purpose:
-- Combines major executive KPIs in one output.
-- =====================================================

SELECT
    SUM(total_sales) AS total_revenue,
    COUNT(*) AS total_orders,
    ROUND(SUM(total_sales) / COUNT(*), 2) AS average_order_value,
    COUNT(DISTINCT customer_name) AS unique_customers,
    COUNT(DISTINCT product_id) AS products_sold,
    MIN(sale_date) AS first_sale_date,
    MAX(sale_date) AS latest_sale_date
FROM sales;


-- =====================================================
-- 6. Monthly Revenue Trend
-- Business Purpose:
-- Helps understand sales growth or decline over time.
-- =====================================================

SELECT
    DATE_FORMAT(sale_date, '%Y-%m-01') AS month_start,
    DATE_FORMAT(sale_date, '%b %Y') AS sale_month,
    SUM(total_sales) AS monthly_revenue,
    COUNT(*) AS total_orders,
    SUM(quantity) AS total_units_sold,
    ROUND(SUM(total_sales) / COUNT(*), 2) AS average_order_value
FROM sales
GROUP BY
    DATE_FORMAT(sale_date, '%Y-%m-01'),
    DATE_FORMAT(sale_date, '%b %Y')
ORDER BY
    month_start;


-- =====================================================
-- 7. Sales by Category
-- Business Purpose:
-- Shows which product categories generate the most revenue.
-- =====================================================

SELECT
    p.category,
    SUM(s.total_sales) AS total_revenue,
    COUNT(s.sale_id) AS total_orders,
    SUM(s.quantity) AS total_units_sold,
    ROUND(SUM(s.total_sales) / COUNT(s.sale_id), 2) AS average_order_value
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.category
ORDER BY
    total_revenue DESC;


-- =====================================================
-- 8. Sales by State
-- Business Purpose:
-- Shows geography-wise revenue performance.
-- Case differences are grouped together using LOWER + TRIM.
-- =====================================================

SELECT
    LOWER(TRIM(state)) AS state_key,
    MIN(TRIM(state)) AS state,
    SUM(total_sales) AS total_revenue,
    COUNT(*) AS total_orders,
    SUM(quantity) AS total_units_sold,
    COUNT(DISTINCT customer_name) AS unique_customers
FROM sales
GROUP BY
    LOWER(TRIM(state))
ORDER BY
    total_revenue DESC;


-- =====================================================
-- 9. Sales by City
-- Business Purpose:
-- Shows city-wise revenue performance.
-- City and state are grouped case-insensitively.
-- =====================================================

SELECT
    LOWER(TRIM(state)) AS state_key,
    MIN(TRIM(state)) AS state,
    LOWER(TRIM(city)) AS city_key,
    MIN(TRIM(city)) AS city,
    SUM(total_sales) AS total_revenue,
    COUNT(*) AS total_orders,
    SUM(quantity) AS total_units_sold
FROM sales
GROUP BY
    LOWER(TRIM(state)),
    LOWER(TRIM(city))
ORDER BY
    total_revenue DESC;


-- =====================================================
-- 10. Top 10 Products by Revenue
-- Business Purpose:
-- Shows highest revenue generating products.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    SUM(s.total_sales) AS total_revenue,
    COUNT(s.sale_id) AS total_orders,
    SUM(s.quantity) AS total_units_sold
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category
ORDER BY
    total_revenue DESC
LIMIT 10;


-- =====================================================
-- 11. Top 10 Products by Order Count
-- Business Purpose:
-- Shows products sold most frequently.
-- Revenue and order count can show different business stories.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    COUNT(s.sale_id) AS total_orders,
    SUM(s.quantity) AS total_units_sold,
    SUM(s.total_sales) AS total_revenue
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category
ORDER BY
    total_orders DESC
LIMIT 10;


-- =====================================================
-- 12. Product Performance Summary
-- Business Purpose:
-- Shows revenue, orders, units sold, and average selling price by product.
-- Includes products with no sales also.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    COUNT(s.sale_id) AS total_orders,
    COALESCE(SUM(s.quantity), 0) AS total_units_sold,
    COALESCE(SUM(s.total_sales), 0) AS total_revenue,
    ROUND(COALESCE(AVG(s.unit_price), 0), 2) AS average_selling_price
FROM products p
LEFT JOIN sales s
    ON p.product_id = s.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category
ORDER BY
    total_revenue DESC;


-- =====================================================
-- 13. Products Without Sales
-- Business Purpose:
-- Finds products that exist in product master but have no sales records.
-- Useful for product coverage and catalog review.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category
FROM products p
LEFT JOIN sales s
    ON p.product_id = s.product_id
WHERE s.sale_id IS NULL
ORDER BY
    p.category,
    p.product_name;


-- =====================================================
-- 14. Product Performance by State
-- Business Purpose:
-- Helps compare how the same product performs across different states.
-- Useful for regional product analysis.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    LOWER(TRIM(s.state)) AS state_key,
    MIN(TRIM(s.state)) AS state,
    COUNT(s.sale_id) AS total_orders,
    SUM(s.quantity) AS total_units_sold,
    SUM(s.total_sales) AS total_revenue,
    ROUND(SUM(s.total_sales) / COUNT(s.sale_id), 2) AS average_order_value
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category,
    LOWER(TRIM(s.state))
ORDER BY
    p.product_name,
    total_revenue DESC;


-- =====================================================
-- 15. Category Performance by State
-- Business Purpose:
-- Shows which product categories perform best in each state.
-- =====================================================

SELECT
    p.category,
    LOWER(TRIM(s.state)) AS state_key,
    MIN(TRIM(s.state)) AS state,
    COUNT(s.sale_id) AS total_orders,
    SUM(s.quantity) AS total_units_sold,
    SUM(s.total_sales) AS total_revenue,
    ROUND(SUM(s.total_sales) / COUNT(s.sale_id), 2) AS average_order_value
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.category,
    LOWER(TRIM(s.state))
ORDER BY
    state,
    total_revenue DESC;


-- =====================================================
-- 16. Highest Revenue Product
-- Business Purpose:
-- Identifies the single best performing product by revenue.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    SUM(s.total_sales) AS total_revenue
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category
ORDER BY
    total_revenue DESC
LIMIT 1;


-- =====================================================
-- 17. Lowest Revenue Product with Sales
-- Business Purpose:
-- Identifies lowest performing product among products that have sales.
-- =====================================================

SELECT
    p.product_id,
    p.product_name,
    p.category,
    SUM(s.total_sales) AS total_revenue
FROM sales s
INNER JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.category
HAVING
    total_revenue > 0
ORDER BY
    total_revenue ASC
LIMIT 1;


-- =====================================================
-- 18. Running Total Sales by Month
-- Business Purpose:
-- Shows cumulative revenue growth over time.
-- Uses window function.
-- =====================================================

SELECT
    month_start,
    sale_month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY month_start
    ) AS running_total_revenue
FROM (
    SELECT
        DATE_FORMAT(sale_date, '%Y-%m-01') AS month_start,
        DATE_FORMAT(sale_date, '%b %Y') AS sale_month,
        SUM(total_sales) AS monthly_revenue
    FROM sales
    GROUP BY
        DATE_FORMAT(sale_date, '%Y-%m-01'),
        DATE_FORMAT(sale_date, '%b %Y')
) monthly_data
ORDER BY
    month_start;


-- =====================================================
-- 19. Month-over-Month Revenue Growth
-- Business Purpose:
-- Shows revenue growth percentage compared to previous month.
-- Uses LAG window function.
-- =====================================================

SELECT
    month_start,
    sale_month,
    monthly_revenue,
    previous_month_revenue,
    monthly_revenue - previous_month_revenue AS revenue_difference,
    ROUND(
        ((monthly_revenue - previous_month_revenue) / previous_month_revenue) * 100,
        2
    ) AS mom_growth_percentage
FROM (
    SELECT
        month_start,
        sale_month,
        monthly_revenue,
        LAG(monthly_revenue) OVER (
            ORDER BY month_start
        ) AS previous_month_revenue
    FROM (
        SELECT
            DATE_FORMAT(sale_date, '%Y-%m-01') AS month_start,
            DATE_FORMAT(sale_date, '%b %Y') AS sale_month,
            SUM(total_sales) AS monthly_revenue
        FROM sales
        GROUP BY
            DATE_FORMAT(sale_date, '%Y-%m-01'),
            DATE_FORMAT(sale_date, '%b %Y')
    ) monthly_summary
) growth_data
ORDER BY
    month_start;


-- =====================================================
-- 20. Revenue Share by Category
-- Business Purpose:
-- Shows each category's contribution to total revenue.
-- =====================================================

SELECT
    category,
    total_revenue,
    ROUND(
        (total_revenue / SUM(total_revenue) OVER ()) * 100,
        2
    ) AS revenue_share_percentage
FROM (
    SELECT
        p.category,
        SUM(s.total_sales) AS total_revenue
    FROM sales s
    INNER JOIN products p
        ON s.product_id = p.product_id
    GROUP BY
        p.category
) category_revenue
ORDER BY
    total_revenue DESC;